version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/jeyhun.info
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      runas: root
      timeout: 300
  AfterInstall:
    - location: scripts/after-install.sh
      runas: ec2-user
      timeout: 300
  ApplicationStart:
    - location: scripts/application-start.sh
      runas: root
      timeout: 60
  ApplicationStop:
    - location: scripts/application-stop.sh
      runas: root
      timeout: 120